services:
  backend:
    build: ./apps/backend
    ports:
      - "${BACKEND_PORT}:4000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/certs:ro
    environment:
      PORT: 4000
