services:
  frontend:
    build: ./apps/frontend
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - ./apps/frontend/.env
    restart: unless-stopped

  backend:
    build: ./apps/backend
    ports:
      - "${BACKEND_PORT}:4000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/certs:ro
    environment:
      PORT: 4000  

  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
